# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160815_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('al margen', 'Al Margen'), ('cyt', 'Ciencia y Tenologia'), ('como nos ven', 'Como Nos Ven'), ('econoinformal', 'Econoinformal'), ('editorial', 'Editorial'), ('el bobo', 'El Bobo'), ('el intruso', 'El Intruso'), ('el w', 'El W'), ('en debate', 'En Deb(A)te'), ('exogeno', 'Exogeno'), ('opinion', 'Opinion'), ('personajes', 'Personajes')], default='', max_length=100),
        ),
    ]
