# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160816_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promoted',
            field=models.BooleanField(default='False'),
        ),
    ]
