# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fuente',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[(b'almargen', b'Al Margen'), (b'cyt', b'Ciencia y Tecnologia'), (b'cnv', b'Como Nos Ven'), (b'econoinf', b'Econoinformal'), (b'editorial', b'Editorial'), (b'elbobo', b'El Bobo'), (b'elintruso', b'El Intruso'), (b'elw', b'El W'), (b'endebate', b'En Deb(A)te'), (b'exogeno', b'Exogeno'), (b'opinion', b'Opinion'), (b'personajes', b'Personajes')], default=b'', max_length=100),
        ),
    ]
