# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170118_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fuente',
            new_name='source_of_the_photo',
        ),
    ]
